title: W. Jason Gilmore
email: wj@wjgilmore.com
description: >- # this means to ignore newlines until "baseurl:"
  Jason Gilmore is the CEO of Treehouse and a bestselling author of several programming books.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wjgilmore
github_username: wjgilmore

# Build settings
markdown: kramdown
remote_theme: sobolevn/sobolevn.github.io
plugins:
  - jekyll-feed
  - jekyll-redirect-from
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
